deel_dbt_project:
  target: default
  outputs:
    default:
      account: 
      type: snowflake
      user: dbt
      password: 
      role: transform
      database: DEEL_TEST
      warehouse: COMPUTE_WH
      schema: raw