deel_dbt_project:
  target: default
  outputs:
    default:
      account: cuuszyb-wi62825
      type: snowflake
      user: dbt
      password: 'dbtPassword123'
      role: transform
      database: DEEL_TEST
      warehouse: COMPUTE_WH
      schema: raw